export { default as Login } from './Login';
export { default as ForgotPassword } from './ForgotPassword'
export { default as Register } from './Register';
export { default as Error } from './Error';
export { default as Landing } from './Landing';
export { default as EmailVerification } from './EmailVerification'
export { default as LinkVerification } from './LinkVerification'
export { default as IndividualLogin } from './IndividualLogin'
export { default as RestaurantHome } from './RestaurantHome'
export { default as IndividualForgotPassword } from './IndividualForgotPassword'
export { default as AdminLogin } from './AdminLogin'